"""Plot Stage 6 held-out fit panels for the supplementary MLP model check.

The figure is a 2 x 4 grid:

- columns: plain magnetic, Lim-style path-label, APMD path-memory, APMD local-ID
- rows: force and displacement measured-vs-predicted fits

Inputs are generated by apmd_stage6_neural_model_check.py.
"""

from __future__ import annotations

from pathlib import Path
import sys

import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import numpy as np
import pandas as pd

import apmd_stage6_neural_model_check as neural


ROOT = Path(__file__).resolve().parent
REPORTS_DIR = ROOT / "reports"

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

PREDICTIONS_CSV = REPORTS_DIR / "apmd_stage6_mlp_predictions.csv"
METRICS_CSV = REPORTS_DIR / "apmd_stage6_mlp_model_metrics.csv"
OUT_PNG = REPORTS_DIR / "apmd_stage6_mlp_fit_grid_2x4.png"
OUT_PDF = REPORTS_DIR / "apmd_stage6_mlp_fit_grid_2x4.pdf"

BLACK = "#222222"
BLUE = "#2c7fb8"
GRAY = "#8a8a8a"
RED = "#c23b3b"
LIGHT_GRAY = "#e7e7e7"
TEXT_GRAY = "#4d4d4d"


MODELS = [
    (
        "plain_magnetic_mlp",
        "Plain magnetic MLP",
        "B only",
    ),
    (
        "lim_style_branch_mlp",
        "Path-label MLP",
        "B + branch label",
    ),
    (
        "apmd_path_memory_mlp",
        "Path-memory MLP",
        "B + path history",
    ),
    (
        "apmd_local_identifiability_mlp",
        "Local-ID MLP",
        "B + path history + local jF/jd",
    ),
]

PATH_COLORS = {
    "direct_loading": BLACK,
    "return_unloading": BLUE,
    "preload_deep": GRAY,
}
PATH_LABELS = {
    "direct_loading": "direct loading",
    "return_unloading": "return unloading",
    "preload_deep": "preload state",
}


def _set_figure_style() -> None:
    plt.rcParams.update(
        {
            "font.family": "DejaVu Sans",
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "axes.linewidth": 0.9,
            "axes.labelsize": 9.5,
            "axes.titlesize": 10.5,
            "xtick.labelsize": 8.5,
            "ytick.labelsize": 8.5,
            "legend.fontsize": 8.5,
            "figure.facecolor": "white",
            "axes.facecolor": "white",
        }
    )


def _axis_limits(values: pd.Series, predictions: pd.Series, pad_frac: float = 0.06) -> tuple[float, float]:
    low = float(min(values.min(), predictions.min()))
    high = float(max(values.max(), predictions.max()))
    span = high - low
    pad = span * pad_frac if span > 0 else 1.0
    return low - pad, high + pad


def _scatter_panel(
    ax: plt.Axes,
    data: pd.DataFrame,
    x_col: str,
    y_col: str,
    lims: tuple[float, float],
    xlabel: str,
    ylabel: str,
    title: str,
    mae_text: str,
) -> None:
    colors = data["path_label"].map(PATH_COLORS).fillna(RED)
    ax.scatter(
        data[x_col],
        data[y_col],
        s=26,
        c=colors,
        edgecolors="white",
        linewidths=0.45,
        alpha=0.84,
        zorder=3,
    )
    ax.plot(lims, lims, color=RED, linewidth=1.0, zorder=2)
    ax.set_xlim(*lims)
    ax.set_ylim(*lims)
    ax.set_aspect("equal", adjustable="box")
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    ax.set_title(title, loc="left", fontweight="bold", pad=7)
    ax.text(
        0.04,
        0.92,
        mae_text,
        transform=ax.transAxes,
        ha="left",
        va="top",
        fontsize=8.5,
        color=TEXT_GRAY,
        bbox={"boxstyle": "round,pad=0.22", "facecolor": "white", "edgecolor": LIGHT_GRAY, "linewidth": 0.5, "alpha": 0.92},
    )
    ax.grid(color=LIGHT_GRAY, linewidth=0.65)
    ax.set_axisbelow(True)
    ax.tick_params(length=3, width=0.8)
    for spine in ["top", "right"]:
        ax.spines[spine].set_visible(False)


def _validate_model_list() -> None:
    expected = [name for name, *_ in neural.mlp_model_specs()]
    actual = [name for name, *_ in MODELS]
    if actual != expected:
        raise RuntimeError(f"MLP fit-grid model order drifted: expected {expected}, got {actual}")


def main() -> None:
    _set_figure_style()
    _validate_model_list()
    predictions = pd.read_csv(PREDICTIONS_CSV)
    metrics = pd.read_csv(METRICS_CSV).set_index("model")

    selected_predictions = predictions[predictions["model"].isin([m[0] for m in MODELS])].copy()
    if selected_predictions.empty:
        raise RuntimeError("No selected MLP model predictions found.")

    f_lims = _axis_limits(selected_predictions["F_N"], selected_predictions["F_pred_N"])
    d_lims = _axis_limits(selected_predictions["d_mm"], selected_predictions["d_pred_mm"], pad_frac=0.08)

    n_cols = len(MODELS)
    fig, axes = plt.subplots(2, n_cols, figsize=(15.4, 7.4), dpi=300)

    for col, (model_name, model_title, model_subtitle) in enumerate(MODELS):
        if model_name not in metrics.index:
            raise RuntimeError(f"Missing metrics for {model_name}")
        data = predictions[predictions["model"] == model_name].copy()
        if data.empty:
            raise RuntimeError(f"Missing predictions for {model_name}")

        m = metrics.loc[model_name]
        _scatter_panel(
            axes[0, col],
            data,
            "F_N",
            "F_pred_N",
            f_lims,
            "measured F (N)",
            "predicted F (N)",
            f"{chr(ord('a') + col)}  {model_title}\n{model_subtitle}",
            f"F MAE = {float(m['F_MAE_N']):.3f} N",
        )
        _scatter_panel(
            axes[1, col],
            data,
            "d_mm",
            "d_pred_mm",
            d_lims,
            "measured d (mm)",
            "predicted d (mm)",
            f"{chr(ord('a') + n_cols + col)}  {model_title}\n{model_subtitle}",
            f"d MAE = {float(m['d_MAE_mm']):.3f} mm",
        )

    legend_handles = [
        Line2D(
            [0],
            [0],
            marker="o",
            linestyle="none",
            markerfacecolor=PATH_COLORS[key],
            markeredgecolor="white",
            markeredgewidth=0.35,
            markersize=7,
            label=PATH_LABELS[key],
        )
        for key in ["direct_loading", "return_unloading", "preload_deep"]
    ]
    legend_handles.append(Line2D([0], [0], color=RED, linewidth=1.1, label="ideal 1:1"))

    train_n = int(metrics.iloc[0]["train_n_states"])
    heldout_n = int(metrics.iloc[0]["heldout_n_states"])
    fig.suptitle(
        "Stage 6.3 MLP held-out fits",
        x=0.055,
        y=0.985,
        ha="left",
        fontsize=14.5,
        fontweight="bold",
    )
    fig.text(
        0.055,
        0.952,
        f"Plain magnetic, branch-label, path-memory and local-identifiability features tested on the same held-out dense-loop states "
        f"(train = {train_n}, held-out = {heldout_n}).",
        ha="left",
        fontsize=9.2,
        color=TEXT_GRAY,
    )
    fig.legend(
        handles=legend_handles,
        loc="upper center",
        bbox_to_anchor=(0.55, 0.902),
        ncol=4,
        frameon=False,
        handlelength=1.8,
        columnspacing=1.8,
    )
    fig.subplots_adjust(left=0.055, right=0.99, top=0.78, bottom=0.075, wspace=0.28, hspace=0.36)

    fig.savefig(OUT_PNG, bbox_inches="tight")
    fig.savefig(OUT_PDF, bbox_inches="tight")
    plt.close(fig)

    print(f"Saved {OUT_PNG.relative_to(ROOT)}")
    print(f"Saved {OUT_PDF.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
