"""Plot Stage 6 held-out fit panels for four ridge model classes.

The figure is a 2 x 4 grid:

- columns: plain magnetic, Lim-style path-label, APMD path-memory, APMD local-ID
- rows: force and displacement measured-vs-predicted fits

Inputs are generated by apmd_stage6_compare_local_identifiability_models.py.
"""

from __future__ import annotations

from pathlib import Path
import sys

import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parent
REPORTS_DIR = ROOT / "reports"

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

PREDICTIONS_CSV = REPORTS_DIR / "apmd_stage6_local_identifiability_predictions.csv"
METRICS_CSV = REPORTS_DIR / "apmd_stage6_local_identifiability_model_metrics.csv"
OUT_PNG = REPORTS_DIR / "apmd_stage6_model_fit_grid_2x4.png"
OUT_PDF = REPORTS_DIR / "apmd_stage6_model_fit_grid_2x4.pdf"

BLACK = "#222222"
BLUE = "#2c7fb8"
GRAY = "#8a8a8a"
RED = "#c23b3b"
LIGHT_GRAY = "#e7e7e7"


MODELS = [
    (
        "plain_magnetic_ridge",
        "Plain magnetic baseline",
        "B only",
    ),
    (
        "lim_style_branch_ridge",
        "Path-label baseline",
        "B + branch label",
    ),
    (
        "apmd_path_memory_ridge",
        "Path-memory model",
        "B + path history",
    ),
    (
        "apmd_local_identifiability_ridge",
        "Local-ID model",
        "B + path history + local jF/jd",
    ),
]

PATH_COLORS = {
    "direct_loading": BLACK,
    "return_unloading": BLUE,
    "preload_deep": GRAY,
}
PATH_LABELS = {
    "direct_loading": "direct loading",
    "return_unloading": "return unloading",
    "preload_deep": "preload state",
}


def _axis_limits(values: pd.Series, predictions: pd.Series, pad_frac: float = 0.06) -> tuple[float, float]:
    low = float(min(values.min(), predictions.min()))
    high = float(max(values.max(), predictions.max()))
    span = high - low
    pad = span * pad_frac if span > 0 else 1.0
    return low - pad, high + pad


def _scatter_panel(
    ax: plt.Axes,
    data: pd.DataFrame,
    x_col: str,
    y_col: str,
    lims: tuple[float, float],
    xlabel: str,
    ylabel: str,
    title: str,
    mae_text: str,
) -> None:
    colors = data["path_label"].map(PATH_COLORS).fillna(RED)
    ax.scatter(
        data[x_col],
        data[y_col],
        s=30,
        c=colors,
        edgecolors="white",
        linewidths=0.35,
        alpha=0.88,
        zorder=3,
    )
    ax.plot(lims, lims, color=RED, linewidth=1.1, zorder=2)
    ax.set_xlim(*lims)
    ax.set_ylim(*lims)
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    ax.set_title(title, loc="left", fontsize=12, fontweight="bold", pad=9)
    ax.text(
        0.04,
        0.92,
        mae_text,
        transform=ax.transAxes,
        ha="left",
        va="top",
        fontsize=9,
        color="#333333",
        bbox={"boxstyle": "round,pad=0.25", "facecolor": "white", "edgecolor": "none", "alpha": 0.82},
    )
    ax.grid(color=LIGHT_GRAY, linewidth=0.8)
    ax.set_axisbelow(True)
    for spine in ["top", "right"]:
        ax.spines[spine].set_visible(False)


def main() -> None:
    predictions = pd.read_csv(PREDICTIONS_CSV)
    metrics = pd.read_csv(METRICS_CSV).set_index("model")

    selected_predictions = predictions[predictions["model"].isin([m[0] for m in MODELS])].copy()
    if selected_predictions.empty:
        raise RuntimeError("No selected model predictions found.")

    f_lims = _axis_limits(selected_predictions["F_N"], selected_predictions["F_pred_N"])
    d_lims = _axis_limits(selected_predictions["d_mm"], selected_predictions["d_pred_mm"], pad_frac=0.08)

    n_cols = len(MODELS)
    fig, axes = plt.subplots(2, n_cols, figsize=(17.2, 8.2), dpi=220)

    for col, (model_name, model_title, model_subtitle) in enumerate(MODELS):
        if model_name not in metrics.index:
            raise RuntimeError(f"Missing metrics for {model_name}")
        data = predictions[predictions["model"] == model_name].copy()
        if data.empty:
            raise RuntimeError(f"Missing predictions for {model_name}")

        m = metrics.loc[model_name]
        _scatter_panel(
            axes[0, col],
            data,
            "F_N",
            "F_pred_N",
            f_lims,
            "measured F (N)",
            "predicted F (N)",
            f"{chr(ord('a') + col)}  {model_title}\n{model_subtitle}",
            f"F MAE = {float(m['F_MAE_N']):.3f} N",
        )
        _scatter_panel(
            axes[1, col],
            data,
            "d_mm",
            "d_pred_mm",
            d_lims,
            "measured d (mm)",
            "predicted d (mm)",
            f"{chr(ord('a') + n_cols + col)}  {model_title}\n{model_subtitle}",
            f"d MAE = {float(m['d_MAE_mm']):.3f} mm",
        )

    legend_handles = [
        Line2D(
            [0],
            [0],
            marker="o",
            linestyle="none",
            markerfacecolor=PATH_COLORS[key],
            markeredgecolor="white",
            markeredgewidth=0.35,
            markersize=7,
            label=PATH_LABELS[key],
        )
        for key in ["direct_loading", "return_unloading", "preload_deep"]
    ]
    legend_handles.append(Line2D([0], [0], color=RED, linewidth=1.1, label="ideal 1:1"))

    train_n = int(metrics.iloc[0]["train_n_states"])
    heldout_n = int(metrics.iloc[0]["heldout_n_states"])
    fig.suptitle(
        "Stage 6.3 held-out fits: plain vs path-label vs path-memory vs local-identifiability",
        x=0.055,
        y=0.99,
        ha="left",
        fontsize=16,
        fontweight="bold",
    )
    fig.text(
        0.055,
        0.955,
        f"Expanded dataset: train = {train_n} states, held-out = {heldout_n} states; predictions from the same held-out dense-loop sessions",
        ha="left",
        fontsize=10,
        color="#555555",
    )
    fig.legend(
        handles=legend_handles,
        loc="upper center",
        bbox_to_anchor=(0.53, 0.915),
        ncol=4,
        frameon=False,
        fontsize=9,
    )
    fig.subplots_adjust(left=0.055, right=0.99, top=0.80, bottom=0.08, wspace=0.26, hspace=0.42)

    fig.savefig(OUT_PNG, bbox_inches="tight")
    fig.savefig(OUT_PDF, bbox_inches="tight")
    plt.close(fig)

    print(f"Saved {OUT_PNG.relative_to(ROOT)}")
    print(f"Saved {OUT_PDF.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
